### ISSUE TITLE
[BUG] Crashes with BetterEnd / BetterNether

### ISSUE THREAD

**Issue by SylisMC** [TeamMidnightDust/RoundTrees#1]
Bootup crash
[latest.log](https://github.com/TeamMidnightDust/RoundTrees/files/5731112/latest.log)

**Comment by pm065** [comment]
Ah, optifine, optifine, optifine... I've heard that it can cause tons of crashes with random things. I know this is several months late, but maybe try without optifine @SylisMC ?

**Comment by Motschen** [comment]
No, I think it's this mod, I encountered it myself. I need to get back to finishing this mod.
