### ISSUE TITLE
Invisible faces next to fences

### ISSUE THREAD

**Issue by MayliSong** [TeamMidnightDust/RoundTrees#2]
The texture pack alone works fine, but adding the mod causes logs to become invisible next to fences.
![image](https://user-images.githubusercontent.com/63749441/106828532-44500600-663f-11eb-93a5-121db1489c7e.png)
I haven't had a chance to check yet, but I think this is somehow related to this mod and Canvas Renderer not playing nice. Disabling the shader packs doesn't fix it but I haven't yet gotten a chance to test disabling the whole Canvas mod.

**Comment by Motschen** [comment]
It has nothing to do with canvas. This is caused by the culling update of the pack and me not getting around to update the mod.
Try disabling the custom outline in the mod's config for now.

**Comment by MayliSong** [comment]
Well, something seems to have fixed it. I tried disabling the custom bounding box and it didn't seem to help at first but I booted it up today and it seems to be fixed. Thank you for your time
