### ISSUE TITLE
Round trees mod didn't fix the sign thing for me :sob:

### ISSUE THREAD

**Issue by miiichael** [TeamMidnightDust/RoundTrees#6]
Fabric, 1.18.1. Modpack pretty much entirely client-side mods, including Iris, indium, lithium, sodium. Patrix resource pack.
![image](https://user-images.githubusercontent.com/4179353/171996331-63d4814f-728c-4c44-ac56-e9785d73a6af.png)

**Comment by Motschen** [comment]
The mod doesn't work in 1.18, it's very outdated.
I'll update it when I have time.

**Comment by miiichael** [comment]
Aww, okay. Out of curiosity (and for the benefit of future googlers :sweat_smile:), which versions does it work with?

**Comment by Motschen** [comment]
1.16.5
